Repository GridTools/gt4py, pull requests merged in 2020-09, with the labels that each got.

#153 stencil generator cli
  .pre-commit-config.yaml
  docs/commandline.rst
  setup.cfg
  src/gt4py/backend/base.py
  src/gt4py/backend/dawn_backends.py
  src/gt4py/backend/gt_backends.py
  src/gt4py/backend/numpy_backend.py
  src/gt4py/caching.py
  src/gt4py/cli.py
  src/gt4py/gtscript.py
  src/gt4py/gtscript_imports.py
  src/gt4py/lazy_stencil.py
  src/gt4py/loader.py
  src/gt4py/stencil_builder.py
  tests/test_unittest/test_backend_api.py
  tests/test_unittest/test_cli.py
  tests/test_unittest/test_gtscript_imports.py
  tests/test_unittest/test_lazy_stencil.py
  tests/test_unittest/test_stencil_builder.py
Labels: module: backend, module: cli

#157 Insert string keys back in argument annotations
  AUTHORS.rst
  src/gt4py/gtscript.py
  tests/test_unittest/test_gtscript_frontend.py
Labels: triage: bug

#116 Fix #115: Emit warning and force explicit domain specification for stencils without an effect
  src/gt4py/analysis/passes.py
  src/gt4py/analysis/transformer.py
  src/gt4py/backend/base.py
  src/gt4py/backend/gt_backends.py
  src/gt4py/frontend/gtscript_frontend.py
  src/gt4py/ir/nodes.py
  src/gt4py/stencil_object.py
  tests/test_integration/test_code_generation.py
Labels: triage: bug

#175 Fix for #173
  src/gt4py/frontend/gtscript_frontend.py
Labels: triage: bug

#176 Fix for #48: Static splitters offset greater than 2
  src/gt4py/ir/utils.py
  tests/reference_cpp_regression/reference.cpp
  tests/test_integration/stencil_definitions.py
  tests/test_integration/test_cpp_regression.py
Labels: module: backend, triage: bug

#169 Fix 143
  .pre-commit-config.yaml
  src/gt4py/analysis/passes.py
  src/gt4py/ir/nodes.py
  tests/analysis_setup.py
  tests/conftest.py
  tests/definition_setup.py
  tests/test_unittest/test_merge_blocks_pass.py
  tests/test_unittest/test_normalize_blocks_pass.py
Labels: module: frontend, triage: bug

#180 Additional code checkers
  .pre-commit-config.yaml
  setup.cfg
  src/gt4py/backend/base.py
  src/gt4py/backend/gt_backends.py
  src/gt4py/caching.py
  src/gt4py/cli.py
  src/gt4py/gtscript_imports.py
  src/gt4py/lazy_stencil.py
  src/gt4py/loader.py
  src/gt4py/stencil_builder.py
  src/gt4py/utils/text.py
  tests/test_unittest/test_backend_api.py
  tests/test_unittest/test_cli.py
  tests/test_unittest/test_gtscript_imports.py
Labels: triage: enhancement

#188 Gitlab ci
  .github/workflows/gt4py-gitlab-ci.yml
  .gitlab-ci.yml
  Dockerfile
  ci/set_github_status.sh
Labels: triage: enhancement

#191 CSCS-CI improvements
  .gitlab-ci.yml
  ci/set_github_status.sh
Labels: triage: enhancement
